ProgSoc/FuzzJudge

README.md

Gave this my best shot. Can maybe be made more clear and/or terse feel free to make any adjustments.

feat(readme): problem format documentation

---

src/main.ts

fix: prevent body from being consumed twice in judge

---

src/http.ts
src/main.ts
src/util.ts

fix: asset whitelist

---

src/db.ts
src/main.ts

fix: admin account remains on server restart

---

.prettierignore
.prettierrc
LICENSE.md
README.md
clients/fj-svelte/.prettierignore
clients/fj-svelte/LICENSE.md
clients/fj-svelte/README.md
clients/fj-svelte/hot-reloader.ts
clients/fj-svelte/index.html
clients/fj-svelte/scoreboard/index.html
clients/fj-svelte/src/api.ts
clients/fj-svelte/src/app.css
clients/fj-svelte/src/main.ts
clients/fj-svelte/src/standalone_scoreboard.ts
clients/fj-svelte/src/utils.ts
clients/fj-svelte/vite.config.ts
format.sh
sample/01-hello/fuzz.ts
sample/01-hello/judge.ts
sample/comp.md
src/auth.ts
src/clock.ts
src/comp.ts
src/db.ts
src/deps.ts
src/http.ts
src/main.ts
src/util.ts

style: Repo-wide prettier
Uses `format.sh` for now, we can adjust that later. But it's good to get consistent formatting out of the way now first.

style: Repo-wide prettier

---

.prettierignore
.prettierrc
clients/fj-svelte/.prettierignore
clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/lib/CompInfo.svelte
clients/fj-svelte/src/lib/Countdown.svelte
clients/fj-svelte/src/lib/ListGroup.svelte
clients/fj-svelte/src/lib/Loading.svelte
clients/fj-svelte/src/lib/Popout.svelte
clients/fj-svelte/src/lib/QuestionButton.svelte
clients/fj-svelte/src/lib/QuestionContents.svelte
clients/fj-svelte/src/lib/Scoreboard.svelte
clients/fj-svelte/src/lib/Sidebar.svelte
clients/fj-svelte/src/lib/SubmissionArea.svelte
clients/fj-svelte/src/utils.ts

style: Svelte formatting
Formatted manually for now. We need to figure out how to install the plugin for the repo later

style: Svelte formatting

---

sample/comp.md
src/clock.ts
src/db.ts
src/deps.ts
src/http.ts
src/main.ts
src/util.ts

refactor: clock backend

---

src/clock.ts
src/comp.ts
src/db.ts
src/score.ts

feat: scoreboard backend

---

src/live/notificationService.ts
src/live/socketData.ts
src/main.ts

feat: Backend socket service scaffold
Creates a notification socket service on the backend. For now it only handles clock.

feat: Backend socket service scaffold

---

src/comp.ts
src/db.ts
src/deps.ts
src/main.ts
src/util.ts

refactor: description files, move render to client

---

clients/fj-svelte/src/api.ts
clients/fj-svelte/src/apiLive.ts
clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/lib/counters/InlineCountdown.svelte
clients/fj-svelte/src/lib/counters/PageCountdown.svelte
clients/fj-svelte/src/utils.ts
src/live/socketData.ts

feat: Frontend live socket service

feat: Frontend live socket service

---

src/main.ts

fix: Delete old websocket port

fix: Delete old websocket port

---

clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/utils.ts

feat: Request questions on the frontend when the competition starts
This will be removed in the future once websocket works
Also fetching questions seems kinda buggy too, but I cbb fixing that atm

feat: Request questions on the frontend when the competition starts

---

clients/fj-svelte/deno.lock
clients/fj-svelte/hot-reloader.ts
clients/fj-svelte/package-lock.json
clients/fj-svelte/package.json
clients/fj-svelte/src/apiLive.ts
clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/lib/ListGroup.svelte
clients/fj-svelte/src/lib/QuestionButton.svelte
clients/fj-svelte/src/lib/QuestionContents.svelte
clients/fj-svelte/src/lib/Scoreboard.svelte
clients/fj-svelte/src/lib/Sidebar.svelte
clients/fj-svelte/src/lib/SubmissionArea.svelte
src/comp.ts
src/main.ts
src/util.ts

fix: Various client-side fixes for the new backend changes
- Fixed questions, scoreboard, state management
- A coupe backend fixes

fix: Various client-side fixes for the new backend changes

---

src/util.ts

fix: Asset whitelist paths

---

src/db.ts

fix: Db query fix

---

src/db.ts
src/main.ts

fix: Other various fixes

---

clients/fj-svelte/src/lib/Client.svelte

fix: Logout void

---

clients/fj-svelte/src/api.ts
clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/lib/QuestionContents.svelte
clients/fj-svelte/src/lib/Scoreboard.svelte
clients/fj-svelte/src/utils.ts
src/score.ts

fix: Completed question status

fix: Completed question status

---

clients/fj-svelte/src/lib/Client.svelte
clients/fj-svelte/src/lib/QuestionContents.svelte

fix: Show countdown instead of broken submission UI when no question is selected

fix: Show countdown instead of broken submission UI when no question is selected

---

clients/fj-svelte/src/lib/Popout.svelte

fix: Popout centering and fullscreen

fix: Popout centering and fullscreen

---

clients/fj-svelte/src/lib/Popout.svelte

fix: Popout minimum view width

fix: Popout minimum view width

---

clients/fj-svelte/src/apiLive.ts
clients/fj-svelte/src/lib/Scoreboard.svelte
clients/fj-svelte/src/lib/SubmissionArea.svelte
src/main.ts

fix: Various on the day fixes

---

server/impl/markdown.ts

Tried to run on windows and the regex didn't match because of this.

Remove carriage returns from problem files
